### ISSUE TITLE
Support HTML5 <datalist>

### ISSUE THREAD

**Issue by enaether** [ma-ha/rest-web-ui#2]
Please support HTML5 <datalist> input field:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist

**Comment by ma-ha** [comment]
v0.9.23: "Text" field supports now "options":

- Test (check out "Role" field): http://mh-svr.de/pong_dev/index.html?layout=tests/action
- Docu: https://github.com/ma-ha/rest-web-ui/tree/master/html/modules/pong-form#text
